### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\michi\Downloads\Valorant-Triggerbot-main\prefire.py", line 134, in <module>     PopOff().hold()   File "C:\Users\michi\Downloads\Valorant-Triggerbot-main\prefire.py", line 120, in hold     if is_pressed(TRIGGER): NameError: name 'is_pressed' is not defined

### ISSUE THREAD

**Issue by michiel1106** [alt-space-c/valorant-triggerbot#13]
basically this error in the title

**Comment by Rayla33** [comment]
same,any fixes?
